application:
  name: nc-executor
apps:
  version: 1.0

spring:
  mail:
    host: 000.000.000.000
  docker:
    compose:
      lifecycle-management: start-only
      start:
        command: up
      file: containers/compose.yml
      enabled: false

  kafka:
    error-handler: kafkaErrorHandler
    bootstrap-servers: '{chipher}139b566f22ca2f881401317facb746c2433252143c36fd43a4a55f0b01128aa9'
    properties:
      schema:
        registry:
          key: schema.registry.url
          url: http://localhost:8081
    consumer:
      group-id: notification_consumer
      max-poll-records: 10
      auto-commit: false
      avro-reader-flag: true
      properties:
        logging:
          enabled: true
      auto-offset-reset: latest
    producer:
      properties:
        auto-register-schema: false
        logging:
          enabled: false
        topics-name:
          pn:
            backend-response-success: stc.nc.queing.response.ackpn
            backend-response-failed: stc.nc.queing.error.ackpn-dlq
          sms:
            backend-response-success: stc.nc.queing.response.acksms
            backend-response-failed: stc.nc.queing.error.acksms-dlq
          validation:
            rejected-reason: '{cipher}0bb47e2aa6c22ec54166adb0d296c1e4ea18d6ffb3a9e5b174fed2a7d5b1b4c9ab29a70f8bc954edfb4accdecbf675cb'

webclient:
  sms:
    baseUri: http://localhost:9500/smsgw/sendSMS
    connectTimeout: 10s # in seconds
  pn:
    baseUri: http://localhost:9700/dngw/sendPushNotify
    connectTimeout: 10s # in seconds
  retry:
    backoffDelay: 1s # in seconds
    maxAttempts: 3
