application:
  name: nc-executor
apps:
  version: 1.0

spring:
  mail:
    host: 000.000.000.000
    # host: 212.118.156.124
  docker:
    compose:
      lifecycle-management: start-only
      start:
        command: up
      file: containers/compose.yml
      enabled: false

  kafka:
    error-handler: kafkaErrorHandler
    #    bootstrap-servers: localhost:9092
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          key: schema.registry.url
          #          url: http://localhost:8081
          url: http://localhost:8081
    consumer:
      group-id: notification_consumer
      max-poll-records: 10
      auto-commit: false
      avro-reader-flag: true
      properties:
        logging:
          enabled: true
      auto-offset-reset: latest
    producer:
      properties:
        auto-register-schema: false
        logging:
          enabled: false
        topics-name:
          pn:
            backend-response-success: stc.nc.queing.response.ackpn
            backend-response-failed: stc.nc.queing.error.ackpn-dlq
          sms:
            backend-response-success: stc.nc.queing.response.acksms
            backend-response-failed: stc.nc.queing.error.acksms-dlq
          validation:
            rejected-reason: stc.nc.queing.reject

webclient:
  sms:
    baseUri: http://172.20.150.69:9500/smsgw/sendSMS
    connectTimeout: 10s # in seconds
  pn:
    baseUri: http://172.20.150.69:9700/dngw/sendPushNotify
    connectTimeout: 10s # in seconds
  retry:
    backoffDelay: 1s # in seconds
    maxAttempts: 3
