docker:
  registry: cicd-tooling-ce.stc.com.sa
  image:
    pullSecret: cicd-ce-dockerhub
    path: stc/nc/microservices/nc-executor
    version: latest
    imagePullPolicy: Always
    fluentdpath: stc/b2c/microservices/fluent-bit
    fluentdversion: latest
  container:
    port: 8080
    targetPort: 8080
kubernetes:
  deployment:
    version: PLACEHOLDER_VERSION
    versionFormatted: PLACEHOLDER_FORMATTED_VERSION
    description: api-exposure-searching-nc-executor
  namespace: nc-ce-sit
  resources:
    limits:
      memory: 1000Mi
      cpu: 1000m
    requests:
      memory: 300Mi
      cpu: 250m
  service:
    type: ClusterIP
    protocol: TCP
    name: 8080-tcp
  ingress:
    endpoint: nc-executor-nc-ce-sit.apps.ocp-dev2.stc.com.sa
    termination: edge
fluentbitconf:
  host: elasticsearch.elastic-app-logging.svc.cluster.local
  port: 9200

sidecar:
  jaegertracing: false
  istio: false
application:
  name: nc-executor
management:
  server:
    port: 8080
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 60
    readinessProbe:
      periodSeconds: 60
      timeoutSeconds: 120
  endpoints:
    web:
      include: health
binder:
  configuration:
    commit_interval_ms: 100

config:
  application:
    security:
      exclusions: /v3/api-docs/**, /swagger*/**, /actuator/**

  spring:
    threads:
      virtual:
        enabled: true
    mail:
      host: 212.118.156.124
    application:
      name: executor
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: user
      password: password
      url: jdbc:mysql://ip:port/db
      hikari:
        idle_timeout: 10000
        minimum_idle: 0

    kafka:
      error_handler: kafkaErrorHandler
      bootstrap_servers: http://10.21.180.97:9092,10.21.180.98:9092,10.21.180.99:9092,10.21.180.100:9092,10.21.180.101:9092,10.21.180.102:9092
      properties:
        schema:
          registry:
            key: schema.registry.url
            url: http://10.21.180.28:8091
      consumer:
        group_id: notification_consumer
        max_poll_records: 10
        auto_commit: false
        avro_reader_flag: true
        properties:
          logging:
            enabled: true
      auto_offset_reset: latest
      producer:
        properties:
          auto_register_schema: false
          logging:
            enabled: false
          topics_name:
            pn:
              backend_response_success: stc.nc.queing.response.ackpn
              backend_response_failed: stc.nc.queing.error.ackpn-dlq
            sms:
              backend_response_success: stc.nc.queing.response.acksms
              backend_response_failed: stc.nc.queing.error.acksms-dlq
            validation:
              rejected_reason: stc.nc.queing.reject

  jpa:
    open_in_view: false
    hibernate:
      ddl_auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    user:
      name: msuser
      password: password
  management:
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true
    info_git_mode: full
    endpoints:
      web_exposure_include: health, metrics, info
    endpoint:
      health_probes_enabled: true
      health_show_details: always
    metrics:
      distribution:
        percentiles_histogram:
          http_server_requests: true
  springdoc:
    api_docs:
      enabled: true
    swagger_ui:
      enabled: true
  enable:
    ms_authorization:
      filter: true
  logging:
    level:
      sa_com_stc_framework_filter_LoggingFilter: DEBUG
      com_stc: DEBUG

  webclient:
    sms:
      baseUri: http://172.20.150.69:9500/smsgw/sendSMS
      connectTimeout: 30s # in seconds
    pn:
      baseUri: http://172.20.150.69:9700/dngw/sendPushNotify
      connectTimeout: 30s # in seconds
    retry:
      backoffDelay: 30s # in seconds
      maxAttempts: 3

  elastic:
    apm:
      enabled: true
      server_url: https://sit-elastic.stc.com.sa:8200
      service_name: nc-executor
      environment: SIT
      application_packages: sa.com.stc.nc.executor
      log_level: CRITICAL
      verify_server_cert: false
      api_key: Zk9OamhJb0JNSkwtaFhsMmJ4Mnc6cFFHUUhjZ0JTR21mRENNNW9IeUhUUQ==

    logstash:
      host: sit-elastic.stc.com.sa
      port: 5051
      user: logstash_http
      pass: cIqiGuzQudg3p-202309

# Autoscaling configuration
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80